name: Redeploy website
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
jobs:
  redeploy_website:
    name: Update website with new doc
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website deployment
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_WEBSITE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/pierre-cm/galbe-website/actions/workflows/static.yml/dispatches \
          -d '{"ref":"main"}'
