name: Release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Version bump scope (patch, minor, major)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      RELEASE_SCOPE: ${{ github.event.inputs.scope }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Git
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
      - name: Install dependencies
        run: |
          bun install
      - name: Release
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          bun run release --increment $RELEASE_SCOPE --ci --no-git.requireCleanWorkingDir
